/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import control.MyExcuteQuery;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Account;

/**
 *
 * @author HAU
 */
public class AccountManagement extends javax.swing.JInternalFrame {

    /**
     * Creates new form PhimManagement1
     */
    MyExcuteQuery myExcuteQuery;
    ArrayList<Account> lst;
    DefaultTableModel dftable;

    public AccountManagement() {
        initComponents();
        myExcuteQuery = new MyExcuteQuery();
        lst = new ArrayList<>();
        dftable = (DefaultTableModel) jTableListAccount.getModel();
        jRadioButtonDisable.setSelected(true);
        loadAllAccount();
    }

    private void loadAllAccount() {
        dftable.setRowCount(0);
        lst = myExcuteQuery.loadAllAccount();
        for (int i = 0; i < lst.size(); i++) {
            int stt = i + 1;
            String username = lst.get(i).getUsername();
            String id = lst.get(i).getIdEmployee();
            String name = lst.get(i).getName();
            String position = lst.get(i).getPosition();
            String status = lst.get(i).isStatus() ? "tạm ngưng" : "kích hoạt";

            Object[] ojb = {stt, username, id, name, position, status};
            dftable.addRow(ojb);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonEnable = new javax.swing.JRadioButton();
        jRadioButtonDisable = new javax.swing.JRadioButton();
        jButtonSetDefaultPassword = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListAccount = new javax.swing.JTable();
        jButtonLoadAll = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Quản lý tài khoản");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Tra cứu tài khoản");

        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_search_magnifying.png"))); // NOI18N
        jButtonSave.setText("Lưu");
        jButtonSave.setBorder(null);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jButtonSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSaveKeyPressed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_refresh_59198.png"))); // NOI18N
        jButtonReset.setText("Đặt lại");
        jButtonReset.setBorder(null);
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jButtonReset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonResetKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Trạng thái");

        buttonGroup1.add(jRadioButtonEnable);
        jRadioButtonEnable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonEnable.setText("Kích hoạt");

        buttonGroup1.add(jRadioButtonDisable);
        jRadioButtonDisable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonDisable.setText("Tạm ngưng");

        jButtonSetDefaultPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSetDefaultPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_goa-account-msn_79748.png"))); // NOI18N
        jButtonSetDefaultPassword.setText("Đặt lại password mặc định");
        jButtonSetDefaultPassword.setBorder(null);
        jButtonSetDefaultPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetDefaultPasswordActionPerformed(evt);
            }
        });
        jButtonSetDefaultPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSetDefaultPasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(0, 57, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSetDefaultPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonEnable)
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonDisable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonEnable)
                    .addComponent(jRadioButtonDisable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSetDefaultPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableListAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableListAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên đăng nhập", "Mã nhân viên", "Tên nhân viên", "Chức vụ", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListAccount.setRowHeight(30);
        jTableListAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListAccountMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListAccount);

        jButtonLoadAll.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLoadAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_ic_find_replace_48px_352364.png"))); // NOI18N
        jButtonLoadAll.setText("Hiện tất cả");
        jButtonLoadAll.setBorder(null);
        jButtonLoadAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadAllActionPerformed(evt);
            }
        });
        jButtonLoadAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonLoadAllKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLoadAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonLoadAll, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        int selectedIndexRow = jTableListAccount.getSelectedRow();
        if (selectedIndexRow == -1) {
            JOptionPane.showMessageDialog(null, "Please choose one row of table!!!");
            return;
        }         
        String username = dftable.getValueAt(selectedIndexRow, 1).toString();
        myExcuteQuery.updateEnable(username, !jRadioButtonEnable.isSelected());
        JOptionPane.showMessageDialog(null, "Save successfully!!!");
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jRadioButtonDisable.setSelected(true);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonSaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSaveKeyPressed
        int selectedIndexRow = jTableListAccount.getSelectedRow();
        if (selectedIndexRow == -1) {
            JOptionPane.showMessageDialog(null, "Please choose one row of table!!!");
            return;
        }         
        String username = dftable.getValueAt(selectedIndexRow, 1).toString();
        myExcuteQuery.updateEnable(username, !jRadioButtonEnable.isSelected());
        JOptionPane.showMessageDialog(null, "Save successfully!!!");
    }//GEN-LAST:event_jButtonSaveKeyPressed

    private void jButtonResetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonResetKeyPressed
        jRadioButtonDisable.setSelected(true);
    }//GEN-LAST:event_jButtonResetKeyPressed

    private void jButtonSetDefaultPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetDefaultPasswordActionPerformed
        int selectedIndexRow = jTableListAccount.getSelectedRow();
        if (selectedIndexRow == -1) {
            JOptionPane.showMessageDialog(null, "Please choose one row of table!!!");
            return;
        }  
        String username = dftable.getValueAt(selectedIndexRow, 1).toString();
        myExcuteQuery.setDefaultPassword(username.trim());
        JOptionPane.showMessageDialog(null, "Change successfully!!!");
    }//GEN-LAST:event_jButtonSetDefaultPasswordActionPerformed

    private void jButtonSetDefaultPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSetDefaultPasswordKeyPressed
        int selectedIndexRow = jTableListAccount.getSelectedRow();
        if (selectedIndexRow == -1) {
            JOptionPane.showMessageDialog(null, "Please choose one row of table!!!");
            return;
        }        
        String username = dftable.getValueAt(selectedIndexRow, 1).toString();
        myExcuteQuery.setDefaultPassword(username);
        JOptionPane.showMessageDialog(null, "Change successfully!!!");
    }//GEN-LAST:event_jButtonSetDefaultPasswordKeyPressed

    private void jTableListAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListAccountMouseClicked
        int selectedIndexRow = jTableListAccount.getSelectedRow();
        if (selectedIndexRow == -1) {
            JOptionPane.showMessageDialog(null, "Please choose one row of table!!!");
            return;
        }
        
        String status = dftable.getValueAt(selectedIndexRow, 5).toString();
        if(status.equals("kích hoạt"))
            jRadioButtonEnable.setSelected(true);
        else jRadioButtonDisable.setSelected(true);
        
        
    }//GEN-LAST:event_jTableListAccountMouseClicked

    private void jButtonLoadAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadAllActionPerformed
        loadAllAccount();
    }//GEN-LAST:event_jButtonLoadAllActionPerformed

    private void jButtonLoadAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonLoadAllKeyPressed
        loadAllAccount();
    }//GEN-LAST:event_jButtonLoadAllKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonLoadAll;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSetDefaultPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonDisable;
    private javax.swing.JRadioButton jRadioButtonEnable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListAccount;
    // End of variables declaration//GEN-END:variables
}
