/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import control.MyConnection;
import control.MyExcuteQuery;
import java.awt.Color;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author HAU
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    ArrayList<String> parameters;
    MyExcuteQuery myExcuteQuery;

    public ChangePassword() {
        initComponents();
        parameters = new ArrayList<>();
        myExcuteQuery = new MyExcuteQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jTextFiledPassword = new javax.swing.JPasswordField();
        jLabelPassword1 = new javax.swing.JLabel();
        jTextFiledPassword1 = new javax.swing.JPasswordField();
        btnChange = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change Password");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 51, 204));
        jLabelTitle.setText("CHANGE PASSWORD");

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelName.setText("UserName");

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldName.setText("Enter User Name");
        jTextFieldName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextFieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNameFocusLost(evt);
            }
        });

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelPassword.setText("Old Password");

        jTextFiledPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFiledPassword.setForeground(new java.awt.Color(204, 204, 204));
        jTextFiledPassword.setText("Enter Password");
        jTextFiledPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextFiledPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFiledPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFiledPasswordFocusLost(evt);
            }
        });

        jLabelPassword1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelPassword1.setText("New Password");

        jTextFiledPassword1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFiledPassword1.setForeground(new java.awt.Color(204, 204, 204));
        jTextFiledPassword1.setText("Enter Password");
        jTextFiledPassword1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        jTextFiledPassword1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFiledPassword1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFiledPassword1FocusLost(evt);
            }
        });

        btnChange.setBackground(new java.awt.Color(0, 153, 204));
        btnChange.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnChange.setForeground(new java.awt.Color(255, 255, 255));
        btnChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.PNG"))); // NOI18N
        btnChange.setText("Change");
        btnChange.setBorder(null);
        btnChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChangeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChangeMouseExited(evt);
            }
        });
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        btnChange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnChangeKeyPressed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(12, 91, 160));
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.PNG"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setBorder(null);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        btnCancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 192, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelPassword)
                                .addGap(271, 271, 271))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTitle)
                                .addGap(203, 203, 203))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(173, 173, 173)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFiledPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextFiledPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addGap(285, 285, 285))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPassword1)
                        .addGap(268, 268, 268))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelTitle)
                .addGap(40, 40, 40)
                .addComponent(jLabelName)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPassword)
                .addGap(18, 18, 18)
                .addComponent(jTextFiledPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPassword1)
                .addGap(23, 23, 23)
                .addComponent(jTextFiledPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNameFocusGained
        if (String.valueOf(jTextFieldName.getText()).trim().equals("Enter User Name")) {
            jTextFieldName.setText("");
        }
        jTextFieldName.setForeground(Color.BLACK);
    }//GEN-LAST:event_jTextFieldNameFocusGained

    private void jTextFieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNameFocusLost
        if (jTextFieldName.getText().trim().equals("")) {
            jTextFieldName.setText("Enter User Name");
        }
        jTextFieldName.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jTextFieldNameFocusLost

    private void jTextFiledPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFiledPasswordFocusGained
        if (String.valueOf(jTextFiledPassword.getPassword()).trim().equals("Enter Password")) {
            jTextFiledPassword.setText("");
        }
        jTextFiledPassword.setForeground(Color.BLACK);
    }//GEN-LAST:event_jTextFiledPasswordFocusGained

    private void jTextFiledPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFiledPasswordFocusLost
        if (String.valueOf(jTextFiledPassword.getPassword()).trim().equals("")) {
            jTextFiledPassword.setText("Enter Password");
        }
        jTextFiledPassword.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jTextFiledPasswordFocusLost

    private void btnChangeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeMouseEntered
        setColor(btnChange);
    }//GEN-LAST:event_btnChangeMouseEntered

    private void btnChangeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeMouseExited
        resetColor(btnChange);
    }//GEN-LAST:event_btnChangeMouseExited

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        setColor(btnCancel);
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        resetColor(btnCancel);
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        parameters.clear();
        if (jTextFieldName.getText().equals("Enter User Name")) {
            jTextFieldName.requestFocus();
        } else if (String.valueOf(jTextFiledPassword.getPassword()).equals("Enter Password")) {
            jTextFiledPassword.requestFocus();
        } else if (String.valueOf(jTextFiledPassword1.getPassword()).equals("Enter Password")) {
            jTextFiledPassword1.requestFocus();
        } else {
            Connection con = MyConnection.getConnection();
            String query1 = "Update account set user_password =? where username =? and user_password =?";
            String query2 = "Select * from account where username =? and user_password =?";
            String username = jTextFieldName.getText().toUpperCase();
            String old_password = String.valueOf(jTextFiledPassword.getPassword()).toUpperCase();
            String new_password = String.valueOf(jTextFiledPassword1.getPassword()).toUpperCase();

            parameters.add(username);
            parameters.add(String.valueOf(old_password.hashCode()));

            if (myExcuteQuery.checkAccount(con, query2, parameters)) {
                myExcuteQuery.updatePassword(con, query1, username, String.valueOf(old_password.hashCode()), String.valueOf(new_password.hashCode()));
                JOptionPane.showMessageDialog(null, "Password has changed!!!");
                jTextFieldName.setText("");
                jTextFiledPassword.setText("");
                jTextFiledPassword1.setText("");
                jTextFieldName.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Can's find username!!!");
                jTextFieldName.setText("");
                jTextFiledPassword.setText("");
                jTextFiledPassword1.setText("");
                jTextFieldName.requestFocus();
            }
        }

    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnChangeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnChangeKeyPressed
        parameters.clear();
        if (jTextFieldName.getText().equals("Enter User Name")) {
            jTextFieldName.requestFocus();
        } else if (String.valueOf(jTextFiledPassword.getPassword()).equals("Enter Password")) {
            jTextFiledPassword.requestFocus();
        } else if (String.valueOf(jTextFiledPassword1.getPassword()).equals("Enter Password")) {
            jTextFiledPassword1.requestFocus();
        } else {
            Connection con = MyConnection.getConnection();
            String query1 = "Update account set user_password =? where username =? and user_password =?";
            String query2 = "Select * from account where username =? and user_password =?";
            String username = jTextFieldName.getText().toUpperCase();
            String old_password = String.valueOf(jTextFiledPassword.getPassword()).toUpperCase();
            String new_password = String.valueOf(jTextFiledPassword1.getPassword()).toUpperCase();

            parameters.add(username);
            parameters.add(String.valueOf(old_password.hashCode()));

            if (myExcuteQuery.checkAccount(con, query2, parameters)) {
                myExcuteQuery.updatePassword(con, query1, username, old_password, new_password);
                JOptionPane.showMessageDialog(null, "Password has changed!!!");
                jTextFieldName.setText("");
                jTextFiledPassword.setText("");
                jTextFiledPassword1.setText("");
                jTextFieldName.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Can's find username!!!");
                jTextFieldName.setText("");
                jTextFiledPassword.setText("");
                jTextFiledPassword1.setText("");
                jTextFieldName.requestFocus();
            }
        }
    }//GEN-LAST:event_btnChangeKeyPressed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelKeyPressed
        this.dispose();
    }//GEN-LAST:event_btnCancelKeyPressed

    private void jTextFiledPassword1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFiledPassword1FocusGained
        if (String.valueOf(jTextFiledPassword1.getPassword()).trim().equals("Enter Password")) {
            jTextFiledPassword1.setText("");
        }
        jTextFiledPassword1.setForeground(Color.BLACK);
    }//GEN-LAST:event_jTextFiledPassword1FocusGained

    private void jTextFiledPassword1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFiledPassword1FocusLost
        if (String.valueOf(jTextFiledPassword1.getPassword()).trim().equals("")) {
            jTextFiledPassword1.setText("Enter Password");
        }
        jTextFiledPassword1.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jTextFiledPassword1FocusLost

    public void setColor(javax.swing.JButton button) {
        button.setBackground(new java.awt.Color(115, 163, 239));
    }

    public void resetColor(javax.swing.JButton button) {
        button.setBackground(new java.awt.Color(12, 91, 160));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChange;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPassword1;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JPasswordField jTextFiledPassword;
    private javax.swing.JPasswordField jTextFiledPassword1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
