/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import control.MyExcuteQuery;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Film;
import model.ShowTimeMovie;

/**
 *
 * @author HAU
 */
public class SellTicketManagement extends javax.swing.JInternalFrame {

    /**
     * Creates new form PhimManagement1
     */
    MyExcuteQuery myExcuteQuery;
    ArrayList<Film> lstFilm;
    ArrayList<ShowTimeMovie> lstShowTime;
    DefaultTableModel dftable;
    DefaultTableModel dftable1;
    
    public SellTicketManagement() {
        initComponents();
        myExcuteQuery = new MyExcuteQuery();
        lstFilm = new ArrayList<>();
        lstShowTime = new ArrayList<>();
        dftable = (DefaultTableModel) jTableListShowTime.getModel();
        dftable1 = (DefaultTableModel) jTableListFilm.getModel();
        loadAllMovie();
    }
    
    private void loadAllMovie() {
        dftable.setRowCount(0);
        lstFilm = myExcuteQuery.loadAllPhim();
        for (int i = 0; i < lstFilm.size(); i++) {
            int id = i + 1;
            String tenPhim = lstFilm.get(i).getTenPhim();
            Object[] ojb = {id, tenPhim};
            dftable1.addRow(ojb);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonChoose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jButtonFind = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListFilm = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListShowTime = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Bán vé");

        jButtonChoose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_ic_find_replace_48px_352364.png"))); // NOI18N
        jButtonChoose.setText("Chọn");
        jButtonChoose.setBorder(null);
        jButtonChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseActionPerformed(evt);
            }
        });
        jButtonChoose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonChooseKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jDateChooser.setDateFormatString("dd-MM-yyyy");
        jDateChooser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonFind.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_search_magnifying.png"))); // NOI18N
        jButtonFind.setText("Tìm kiêm");
        jButtonFind.setBorder(null);
        jButtonFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindActionPerformed(evt);
            }
        });
        jButtonFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonFindKeyPressed(evt);
            }
        });

        jTableListFilm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableListFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên phim"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListFilm.setRowHeight(30);
        jScrollPane2.setViewportView(jTableListFilm);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFind, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableListShowTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableListShowTime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phim", "Tên phim", "Thời lượng", "Định dạng", "Ngày chiếu", "Giờ chiếu", "Rạp", "Nhãn", "Mã KTG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListShowTime.setRowHeight(30);
        jScrollPane1.setViewportView(jTableListShowTime);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseActionPerformed
        int selectedIndexRow = jTableListShowTime.getSelectedRow();
    }//GEN-LAST:event_jButtonChooseActionPerformed

    private void jButtonFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindActionPerformed
        dftable.setNumRows(0);
        int selectedIndexRow = jTableListFilm.getSelectedRow();
        if (selectedIndexRow == -1) {
            JOptionPane.showMessageDialog(null, "Please choose film!!!");
            return;
        }
        String name = dftable1.getValueAt(selectedIndexRow, 1).toString();
        lstShowTime = myExcuteQuery.loadAllShowTimeMovie();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        
        for (int i = 0; i < lstShowTime.size(); i++) {
            Date date = jDateChooser.getDate();
            if (date.equals(lstShowTime.get(i).getDate()) && name.equals(lstShowTime.get(i).getNameFilm())) {
                int id = i + 1;
                String maPhim = lstShowTime.get(i).getIdFilm();
                String tenPhim = lstShowTime.get(i).getNameFilm();
                String thoiLuong = lstShowTime.get(i).getDuration();
                String dinh_dang = lstShowTime.get(i).getFormat();
                String ngay_chieu = formatter.format(lstShowTime.get(i).getDate());
                String gio_chieu = lstShowTime.get(i).getTime();
                String rap = lstShowTime.get(i).getRoom();
                String maNhan = lstShowTime.get(i).getLabel();
                String maKTG = lstShowTime.get(i).getIdKTG();
                
                Object[] ojb = {id, maPhim, tenPhim, thoiLuong, dinh_dang, ngay_chieu, gio_chieu, rap, maNhan, maKTG};
                dftable.addRow(ojb);
            }
        }
    }//GEN-LAST:event_jButtonFindActionPerformed

    private void jButtonFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonFindKeyPressed
        int selectedIndexRow = jTableListFilm.getSelectedRow();
        if (selectedIndexRow == -1) {
            JOptionPane.showMessageDialog(null, "Please choose one row of table!!!");
            return;
        }
        String name = dftable1.getValueAt(selectedIndexRow, 1).toString();
        dftable.setNumRows(0);
        lstShowTime = myExcuteQuery.loadAllShowTimeMovie();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        
        for (int i = 0; i < lstShowTime.size(); i++) {
            Date date = jDateChooser.getDate();
            if (date.equals(lstShowTime.get(i).getDate()) && name.equals(lstShowTime.get(i).getNameFilm())) {
                int id = i + 1;
                String maPhim = lstShowTime.get(i).getIdFilm();
                String tenPhim = lstShowTime.get(i).getNameFilm();
                String thoiLuong = lstShowTime.get(i).getDuration();
                String dinh_dang = lstShowTime.get(i).getFormat();
                String ngay_chieu = formatter.format(lstShowTime.get(i).getDate());
                String gio_chieu = lstShowTime.get(i).getTime();
                String rap = lstShowTime.get(i).getRoom();
                String maNhan = lstShowTime.get(i).getLabel();
                String maKTG = lstShowTime.get(i).getIdKTG();
                
                Object[] ojb = {id, maPhim, tenPhim, thoiLuong, dinh_dang, ngay_chieu, gio_chieu, rap, maNhan, maKTG};
                dftable.addRow(ojb);
            }
        }
    }//GEN-LAST:event_jButtonFindKeyPressed

    private void jButtonChooseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonChooseKeyPressed
        
    }//GEN-LAST:event_jButtonChooseKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChoose;
    private javax.swing.JButton jButtonFind;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListFilm;
    private javax.swing.JTable jTableListShowTime;
    // End of variables declaration//GEN-END:variables
}
